---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: src/content/data
  label: Data
  create: all
  match: "**/*"
  new_doc_ext: json
- type: directory
  path: src/content
  label: Content
  create: all
  match: "**/*"
  exclude: data/**.*
  new_doc_ext: md
upload_dir: https://github.com/wernerglinka/metalsmith-forestry-starter/tree/main/src/assets/images
public_path: "/assets/images"
front_matter_path: ''
use_front_matter_path: true
file_template: ":filename:"
build:
  preview_output_directory: build
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:16
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run fpreview
